# Generated by Django 5.2.9 on 2025-12-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'created_at'], name='login_attem_usernam_2b6fde_idx'), models.Index(fields=['ip_address', 'created_at'], name='login_attem_ip_addr_f68fb5_idx'), models.Index(fields=['tenant_id', 'success', 'created_at'], name='login_attem_tenant__cbac2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, help_text='Username cached for historical reference', max_length=150)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PERMISSION_GRANT', 'Permission Grant'), ('PERMISSION_REVOKE', 'Permission Revoke')], db_index=True, max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('resource_type', models.CharField(db_index=True, help_text='Type of resource (cached from content_type)', max_length=100)),
                ('resource_id', models.CharField(db_index=True, help_text='ID of resource (for quick filtering)', max_length=100)),
                ('old_values', models.JSONField(blank=True, help_text='Previous values (for updates)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='New values (for creates/updates)', null=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='Unique request ID for tracing', max_length=100)),
                ('session_id', models.CharField(blank=True, help_text='User session ID', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (e.g., API endpoint, method)')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id', 'created_at'], name='audit_logs_tenant__0b1a88_idx'), models.Index(fields=['user', 'created_at'], name='audit_logs_user_id_fbfd51_idx'), models.Index(fields=['resource_type', 'resource_id', 'created_at'], name='audit_logs_resourc_43354a_idx'), models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'), models.Index(fields=['tenant_id', 'action', 'created_at'], name='audit_logs_tenant__b6d72a_idx'), models.Index(fields=['tenant_id', 'resource_type', 'created_at'], name='audit_logs_tenant__a1ee4c_idx'), models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx')],
            },
        ),
    ]
