# Generated by Django 5.2.9 on 2025-12-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('respondent_email', models.EmailField(blank=True, db_index=True, help_text='For anonymous responses', max_length=254)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], db_index=True, default='in_progress', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='When response was finalized', null=True)),
                ('resume_token', models.CharField(db_index=True, help_text='Token for resuming partial submissions', max_length=100, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional response metadata (device info, referrer, etc.)')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.survey')),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user (optional for anonymous surveys)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'survey_responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartialResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(help_text='Serialized response data: {field_id: value, ...}')),
                ('progress_percentage', models.PositiveIntegerField(default=0, help_text='Completion percentage (0-100)')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this partial response expires')),
                ('last_accessed_at', models.DateTimeField(auto_now=True)),
                ('current_section', models.ForeignKey(blank=True, help_text='Last section user was on', null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.section')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partial_snapshots', to='responses.surveyresponse')),
            ],
            options={
                'db_table': 'partial_responses',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_datetime', models.DateTimeField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, help_text='For complex values like multiple choice, matrix, etc.', null=True)),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether value_text is encrypted')),
                ('file_url', models.URLField(blank=True, help_text='S3/cloud storage URL for file uploads', max_length=1000)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='surveys.field')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='responses.surveyresponse')),
            ],
            options={
                'db_table': 'survey_response_items',
                'ordering': ['response', 'field'],
            },
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['survey', 'status', 'created_at'], name='survey_resp_survey__ab5268_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['user', 'survey'], name='survey_resp_user_id_c5b177_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['tenant_id', 'status'], name='survey_resp_tenant__f34372_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['submitted_at'], name='survey_resp_submitt_c31738_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['created_at', 'survey'], name='survey_resp_created_6e7c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='partialresponse',
            index=models.Index(fields=['response', 'updated_at'], name='partial_res_respons_562807_idx'),
        ),
        migrations.AddIndex(
            model_name='partialresponse',
            index=models.Index(fields=['expires_at'], name='partial_res_expires_552430_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponseitem',
            index=models.Index(fields=['response', 'field'], name='survey_resp_respons_d9cd63_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponseitem',
            index=models.Index(fields=['field', 'created_at'], name='survey_resp_field_i_52da83_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponseitem',
            index=models.Index(fields=['field', 'value_text'], name='survey_resp_field_i_febb3b_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponseitem',
            index=models.Index(fields=['field', 'value_number'], name='survey_resp_field_i_e0a84d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surveyresponseitem',
            unique_together={('response', 'field')},
        ),
    ]
