# Generated by Django 5.2.9 on 2025-12-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_conditional', models.BooleanField(default=False, help_text='Whether this section visibility depends on other field values')),
            ],
            options={
                'db_table': 'survey_sections',
                'ordering': ['survey', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=500)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('number', 'Number'), ('email', 'Email'), ('phone', 'Phone'), ('date', 'Date'), ('datetime', 'Date & Time'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('dropdown', 'Dropdown'), ('file_upload', 'File Upload'), ('rating', 'Rating'), ('slider', 'Slider'), ('matrix', 'Matrix'), ('boolean', 'Yes/No')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('placeholder', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=False)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('regex_pattern', models.CharField(blank=True, max_length=500)),
                ('is_conditional', models.BooleanField(db_index=True, default=False, help_text='Whether this field visibility depends on other field values')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Encrypt responses to this field at rest')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional field configuration (e.g., min/max for rating, step for slider)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='surveys.section')),
            ],
            options={
                'db_table': 'survey_fields',
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ConditionalLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('show', 'Show Field/Section'), ('hide', 'Hide Field/Section'), ('require', 'Make Required'), ('skip_to', 'Skip to Section')], max_length=20)),
                ('condition', models.JSONField(help_text='Conditional expression in JSON format')),
                ('priority', models.PositiveIntegerField(default=0, help_text='Higher priority rules execute first')),
                ('target_field', models.ForeignKey(blank=True, help_text='Field affected by this logic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_targets', to='surveys.field')),
                ('trigger_field', models.ForeignKey(help_text='Field whose value triggers this logic', on_delete=django.db.models.deletion.CASCADE, related_name='conditional_triggers', to='surveys.field')),
                ('target_section', models.ForeignKey(blank=True, help_text='Section affected by this logic', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conditional_targets', to='surveys.section')),
            ],
            options={
                'db_table': 'conditional_logic',
                'ordering': ['-priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active_version', models.BooleanField(db_index=True, default=True, help_text='Only one version should be active at a time')),
                ('tenant_id', models.CharField(db_index=True, help_text='For multi-tenant isolation', max_length=100)),
                ('allow_multiple_submissions', models.BooleanField(default=False)),
                ('allow_partial_submissions', models.BooleanField(default=True)),
                ('submission_deadline', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional survey configuration')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys_created', to=settings.AUTH_USER_MODEL)),
                ('parent_survey', models.ForeignKey(blank=True, help_text='Reference to original survey for version tracking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='surveys.survey')),
            ],
            options={
                'db_table': 'surveys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='surveys.survey'),
        ),
        migrations.CreateModel(
            name='FieldDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependency_type', models.CharField(choices=[('conditional_display', 'Conditional Display'), ('conditional_validation', 'Conditional Validation'), ('calculated_value', 'Calculated Value')], max_length=50)),
                ('dependent_field', models.ForeignKey(help_text='Field that depends on source_field', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_to', to='surveys.field')),
                ('source_field', models.ForeignKey(help_text='Field that is depended upon', on_delete=django.db.models.deletion.CASCADE, related_name='dependencies_from', to='surveys.field')),
            ],
            options={
                'db_table': 'field_dependencies',
                'indexes': [models.Index(fields=['source_field', 'dependency_type'], name='field_depen_source__192b5c_idx'), models.Index(fields=['dependent_field'], name='field_depen_depende_26590a_idx')],
                'unique_together': {('source_field', 'dependent_field', 'dependency_type')},
            },
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=500)),
                ('value', models.CharField(max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_exclusive', models.BooleanField(default=False, help_text='For multiple choice: selecting this clears other options')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.field')),
            ],
            options={
                'db_table': 'field_options',
                'ordering': ['field', 'order'],
                'indexes': [models.Index(fields=['field', 'order'], name='field_optio_field_i_3d5f21_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['section', 'order'], name='survey_fiel_section_0912ee_idx'),
        ),
        migrations.AddIndex(
            model_name='field',
            index=models.Index(fields=['field_type', 'is_conditional'], name='survey_fiel_field_t_5aeceb_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionallogic',
            index=models.Index(fields=['trigger_field', 'priority'], name='conditional_trigger_1e55b9_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionallogic',
            index=models.Index(fields=['target_field'], name='conditional_target__1cc4fe_idx'),
        ),
        migrations.AddIndex(
            model_name='conditionallogic',
            index=models.Index(fields=['target_section'], name='conditional_target__7ea635_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['tenant_id', 'status', 'is_active_version'], name='surveys_tenant__a2db9f_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['parent_survey', 'version'], name='surveys_parent__97c30e_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by', 'status'], name='surveys_created_7502a8_idx'),
        ),
        migrations.AddConstraint(
            model_name='survey',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active_version', True)), fields=('parent_survey', 'is_active_version'), name='unique_active_version_per_survey'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['survey', 'order'], name='survey_sect_survey__815b1e_idx'),
        ),
    ]
