# Generated by Django 5.2.9 on 2025-12-23 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codename', models.CharField(db_index=True, help_text='Dot notation: resource.action (e.g., survey.create)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('resource', models.CharField(db_index=True, help_text='Resource type (survey, submission, analytics, etc.)', max_length=50)),
                ('action', models.CharField(help_text='Action on resource (create, view, edit, delete, etc.)', max_length=50)),
                ('is_system_permission', models.BooleanField(default=False, help_text='System permissions cannot be deleted')),
            ],
            options={
                'db_table': 'permissions',
                'ordering': ['resource', 'action'],
                'indexes': [models.Index(fields=['resource', 'action'], name='permissions_resourc_2eec83_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Role name (e.g., Admin, Survey Creator, Analyst)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('tenant_id', models.CharField(db_index=True, help_text='Empty for global roles, specific for tenant roles', max_length=100)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted')),
                ('parent_role', models.ForeignKey(blank=True, help_text='Parent role (inherits all permissions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_roles', to='rbac.role')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='rbac.permission')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant_id', models.CharField(db_index=True, help_text='Tenant this role applies to', max_length=100)),
                ('scope', models.JSONField(blank=True, default=dict, help_text='Additional scope restrictions (e.g., {"survey_ids": [1, 2, 3]})')),
                ('valid_from', models.DateTimeField(blank=True, help_text='When this role becomes active', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When this role expires', null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='rbac.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_roles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['tenant_id', 'name'], name='roles_tenant__74cc42_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'tenant_id')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'tenant_id'], name='user_roles_user_id_93c493_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'tenant_id'], name='user_roles_role_id_283544_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'role', 'tenant_id'], name='user_roles_user_id_162aab_idx'),
        ),
    ]
